### ISSUE TITLE
Is there a way to use amagama with MySql?

### ISSUE THREAD

**Issue by memoday** [translate/amagama#3205]
Hello team,

I don't want to install PostgreSQL along with MySQL. I am afraid it may ruin MySQL setup or already running databases? Is there instructions on how to use amaGama with MySQL? Is it OK to install PostgreSQL along with MySQL on the same server or is it going to hit the performance? Please let me know what you think.

Thanks,
Mohamned

**Comment by unho** [comment]
No, amaGama uses exclusively PostgreSQL as it depends on some features that only are supported by PostgreSQL.

Running PostgreSQL and MySQL won't ruin MySQL. It may have some impact on performance since you will be running extra software. Depending on how many resources you machine has, and how much do you use that machine, you might want to consider putting them on separate machines. But for a machine that is not used intensively it shouldn't be such a big deal.

**Comment by memoday** [comment]
Thank you so much for your reply.
