### ISSUE TITLE
Incorrect quality information via API

### ISSUE THREAD

**Issue by mathjazz** [translate/amagama#3208]
Quality information returned from the following API request seems wrong:
https://amagama-live.translatehouse.org/api/v1/en/sl/unit/Change/

```json
[{
    "quality": 85.71428571428572,
    "rank": 100.0,
    "source": "Change",
    "target": "Spremeni"
}, {
    "quality": 85.71428571428572,
    "rank": 100.0,
    "source": "Change",
    "target": "Sprememba"
}]
```

It should be 100, like on https://amagama-live.translatehouse.org/.

**Comment by unho** [comment]
It is curious, https://amagama-live.translatehouse.org/api/v1/en/sl/unit/?source=Change and https://amagama-live.translatehouse.org/api/v1/en/sl/unit/Change/ do return different results.

**Comment by unho** [comment]
@mathjazz Closing this as a non issue since you are using:

https://amagama-live.translatehouse.org/api/v1/en/sl/unit/Change/

instead of the correct

https://amagama-live.translatehouse.org/api/v1/en/sl/unit/Change

You can see that https://amagama-live.translatehouse.org/ returns the same results if you search by "Change/" instead of "Change".
